config/routes.rb
Rails.application.routes.draw do
  root 'galleries#index'

  resources :galleries, format: false do
    resources :photos, except: %i[index]
  end

  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
# == Schema Information
#
# Table name: galleries
#
#  id                :bigint           not null, primary key
#  name              :string           not null
#  short_description :text             not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  user_id           :bigint           not null
#
# Indexes
#
#  index_galleries_on_name     (name) UNIQUE
#  index_galleries_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Gallery < ApplicationRecord
  validates_uniqueness_of :name, presence: true
  validates :short_description, presence: true
  validates :user_id, presence: true

  belongs_to :user
  has_many :photos, dependent: :destroy
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id                 :bigint           not null, primary key
#  image_content_type :string           not null
#  image_file_name    :string           not null
#  image_file_size    :bigint           not null
#  image_updated_at   :datetime         not null
#  name               :string
#  shooting_date      :datetime
#  short_description  :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  gallery_id         :bigint           not null
#
# Indexes
#
#  index_photos_on_gallery_id  (gallery_id)
#  index_photos_on_name        (name) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (gallery_id => galleries.id)
#
class Photo < ApplicationRecord
  validates_uniqueness_of :name, presence: true
  validates :gallery_id, presence: true

  belongs_to :gallery
  has_attached_file :image
  validates_attachment_content_type :image, content_type: %r{\Aimage/.*\z}
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :galleries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: %i[show edit update destroy]

  # GET /galleries or /galleries.json
  def index
    @galleries = Gallery.where(user_id: current_user.id)
  end

  # GET /galleries/1 or /galleries/1.json
  def show
    @photos = Photo.where(gallery_id: params[:id])
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit; end

  # POST /galleries or /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to gallery_url(@gallery), notice: 'Gallery was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1 or /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to gallery_url(@gallery), notice: 'Gallery was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1 or /galleries/1.json
  def destroy
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Gallery was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_gallery
    @gallery = Gallery.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def gallery_params
    params.fetch(:gallery) { {} }.permit(:name, :short_description).merge({ user_id: current_user.id })
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[show edit update destroy]

  # GET /photos/1 or /photos/1.json
  def show; end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit; end

  # POST /photos or /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html do
          redirect_to gallery_url(params[:gallery_id]), notice: 'Photo was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1 or /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html do
          redirect_to gallery_photo_url(gallery_id: params[:gallery_id], id: @photo.id),
                      notice: 'Photo was successfully updated.'
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to gallery_url(params[:gallery_id]), notice: 'Photo was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_photo
    @photo = Photo.find_by(id: params[:id], gallery_id: params[:gallery_id])

    raise ActiveRecord::RecordNotFound if @photo.nil?
  end

  # Only allow a list of trusted parameters through.
  def photo_params
    result = params.fetch(:photo) { {} }
                   .permit(:name, :shooting_date, :short_description, :image)
                   .merge({ gallery_id: params[:gallery_id] })

    result.delete(:image) if result[:image].nil?

    result
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
  def url_submit(photo, gallery_id)
    if photo.new_record?
      gallery_photos_path(gallery_id: gallery_id)
    else
      gallery_photo_path(id: photo.id, gallery_id: gallery_id)
    end
  end
end

app/views/galleries/_form.html.erb
<%= simple_form_for(@gallery) do |f| %>
  <%= f.error_notification %>
  <% f.object.errors.full_messages.each do |msg| %>
    <p class="text-danger">- <%= msg %></p>
  <% end %>

  <div class="form-group">
    <%= f.input :name, 
                required: true,
                autofocus: true,
                input_html: { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= f.input :short_description, 
                required: true,
                input_html: { class: "form-control" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<div class="form-center">
  <div class="form-center-content">
    <div class="w-30">
      <h2>Editing Gallery</h2>

      <%= render 'form', gallery: @gallery %>

      <%= link_to 'Show', @gallery %> |
      <%= link_to 'Back', galleries_path %>
    </div>
  </div>
</div>

app/views/galleries/index.html.erb
<div class="container bg-white pt-5 pb-5">
  <h1>
    Galleries 
    <span class="link-in-title"><%= link_to 'New Gallery', new_gallery_path %></span>
  </h1>

  <div class="row">
    <% @galleries.each do |gallery| %>
      <div class="col-md-3">
        <div class="card" style="width: 100%">
          <div class="card-body">
            <h5 class="card-title"><%= gallery.name %></h5>
            <p class="card-text"><%= gallery.short_description %></p>
            <div class="action-links">
              <%= link_to 'View photos', gallery %> |
              <%= link_to 'Edit', edit_gallery_path(gallery) %> |
              <%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/galleries/new.html.erb
<div class="form-center">
  <div class="form-center-content">
    <div class="w-30">
      <h2>New Gallery</h2>

      <%= render 'form', gallery: @gallery %>

      <%= link_to 'Back', galleries_path %>
    </div>
  </div>
</div>

app/views/galleries/show.html.erb
<div class="container bg-white p-5">
  <%= link_to 'Back to list', galleries_path %>

  <h1>
    Photos in gallery <span class="text-info"><%= @gallery.name %></span>
    <span class="link-in-title"><%= link_to 'Add new photo', new_gallery_photo_path(@gallery) %></span>
  </h1>

  <div class="row">
    <% @photos.each do |photo| %>
      <div class="col-md-3 photo">
        <div class="card" style="width: 100%">
          <div class="card-body">
            <a href="<%= photo.image.url %>" target="_blank">
              <div class="img-box" style="background-image: url('<%= photo.image.url %>')"></div>
            </a>

            <h5 class="card-title"><%= photo.name %></h5>
            <p class="card-text"><%= photo.short_description %></p>

            <div class="action-links">
              <%= link_to 'Details', gallery_photo_path(gallery_id: @gallery.id, id: photo.id) %> |
              <%= link_to 'Edit', edit_gallery_photo_path(gallery_id: @gallery.id, id: photo.id) %> |
              <%= link_to 'Destroy', gallery_photo_path(gallery_id: @gallery.id, id: photo.id), method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_breadcrumb.html.erb
<div class="breadcrumb">
  <%=link_to 'Log out', destroy_user_session_path, method: :delete if current_user.present? %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chau Duc Tai - User Galleries</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render './layouts/breadcrumb' %>

    <%= yield %>
  </body>
</html>

app/views/photos/_form.html.erb
<%= simple_form_for(@photo, url: url_submit(@photo, params[:gallery_id])) do |f| %>
  <%= f.error_notification %>
  <% f.object.errors.full_messages.each do |msg| %>
    <p class="text-danger">- <%= msg %></p>
  <% end %>

  <div class="form-group">
    <%= f.input :name, 
                required: true,
                autofocus: true,
                input_html: { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= f.input :image,
                as: :file,
                required: true,
                input_html: { class: "form-control" } %>
  </div>

  <div class="form-group">
    <label><%= :shooting_date.to_s.humanize %> </label>
    <%= f.datetime_field :shooting_date, 
                required: false,
                class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :short_description, 
                required: false,
                input_html: { class: "form-control" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<div class="form-center">
  <div class="form-center-content">
    <div class="w-30">
      <h1>Editing Photo</h1>

      <%= render 'form', photo: @photo %>

      <%= link_to 'Show', gallery_photo_path(gallery_id: params[:gallery_id], id: @photo.id) %> |
      <%= link_to 'Back', gallery_path(params[:gallery_id]) %>
    </div>
  </div>
</div>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<div class="form-center">
  <div class="form-center-content">
    <div class="w-30">
      <h2>New Photo</h2>

      <%= render 'form', photo: @photo %>

      <%= link_to 'Back', gallery_photos_path %>
    </div>
  </div>
</div>

app/views/photos/show.html.erb
<div class="container bg-white p-5">
  <%= link_to 'Back to gallery', gallery_path(id: params[:gallery_id]) %>
  <%= link_to 'Edit', edit_gallery_photo_path(gallery_id: params[:gallery_id], id: @photo.id), class: 'float-right' %>
  
  <div class="row">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Info</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <th scope="row">Gallery</th>
          <td><%= link_to @photo.gallery.name, gallery_photo_path(gallery_id: params[:gallery_id]) %></td>
        </tr>
        <tr>
          <th scope="row">Name</th>
          <td><%= @photo.name %></td>
        </tr>
        <tr>
          <th scope="row">Short description</th>
          <td><%= @photo.short_description %></td>
        </tr>
      </tbody>
    </table>

    <div class="col-md-12">
      <h5>Photo</h5>
    </div>

    <%= image_tag @photo.image.url %>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<hr>

<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>